Fix other bug mentioned in #183
In #183, I also found another bug that I didn’t report as a separate
issue:
https://github.com/ceylon/ceylon-sdk/issues/183#issuecomment-32129109
Error: LinkedList.delete() would return the element *before* the deleted
one
Cause: @gavinking changed the iteration (to eliminate a ‘prev’ variable)
by always checking one element ahead, but (presumably) forgot to update
the return statement to reflect this change
Fix: Return ‘rest?.element’ instead of ‘cell.element’

Also adds a test case for the bug.